Repository netty/netty, pull requests merged in 2018-12, with the labels that each got.

#8620 ChannelInitializer may be invoked multiple times when used with custo…
  transport/src/main/java/io/netty/channel/ChannelInitializer.java
  transport/src/test/java/io/netty/channel/ChannelInitializerTest.java
Labels: defect

#8645 ReadTimeoutHandler - missing ) within JavaDoc example
  handler/src/main/java/io/netty/handler/timeout/ReadTimeoutHandler.java
Labels: cleanup

#8647 Explict always call ctx.read() when AUTO_READ is false and HTTP/2 is …
  codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java
  codec-http2/src/test/java/io/netty/handler/codec/http2/Http2ConnectionHandlerTest.java
Labels: cleanup

#8650 Handling AUTO_READ should not be the responsibility of DefaultChannel…
  codec-http2/src/main/java/io/netty/handler/codec/http2/Http2MultiplexCodec.java
  transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollChannel.java
  transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollServerChannel.java
  transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollStreamChannel.java
  transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollDatagramChannel.java
  transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollDomainSocketChannel.java
  transport-native-kqueue/src/main/java/io/netty/channel/kqueue/AbstractKQueueChannel.java
  transport-native-kqueue/src/main/java/io/netty/channel/kqueue/AbstractKQueueServerChannel.java
  transport-native-kqueue/src/main/java/io/netty/channel/kqueue/AbstractKQueueStreamChannel.java
  transport-native-kqueue/src/main/java/io/netty/channel/kqueue/KQueueDatagramChannel.java
  transport-native-kqueue/src/main/java/io/netty/channel/kqueue/KQueueDomainSocketChannel.java
  transport/src/main/java/io/netty/channel/AbstractChannel.java
  transport/src/main/java/io/netty/channel/DefaultChannelPipeline.java
  transport/src/main/java/io/netty/channel/embedded/EmbeddedChannel.java
  transport/src/main/java/io/netty/channel/local/LocalChannel.java
  transport/src/main/java/io/netty/channel/local/LocalServerChannel.java
  transport/src/main/java/io/netty/channel/nio/AbstractNioByteChannel.java
  transport/src/main/java/io/netty/channel/nio/AbstractNioChannel.java
  transport/src/main/java/io/netty/channel/nio/AbstractNioMessageChannel.java
  transport/src/test/java/io/netty/channel/DefaultChannelPipelineTailTest.java
Labels: cleanup

#8665 Fix ClassCastException and native crash when using kqueue transport.
  transport-native-kqueue/src/main/c/netty_kqueue_eventarray.c
  transport-native-kqueue/src/main/java/io/netty/channel/kqueue/AbstractKQueueChannel.java
  transport-native-kqueue/src/main/java/io/netty/channel/kqueue/KQueueEventArray.java
  transport-native-kqueue/src/main/java/io/netty/channel/kqueue/KQueueEventLoop.java
Labels: defect

#8651 Added "UTF-8 only" comments to three decoders.
  codec/src/main/java/io/netty/handler/codec/LineBasedFrameDecoder.java
  codec/src/main/java/io/netty/handler/codec/json/JsonObjectDecoder.java
  codec/src/main/java/io/netty/handler/codec/xml/XmlFrameDecoder.java
Labels: documentation
