Repository netty/netty, pull requests merged in 2018-03, with the labels that each got.

#7743 Flush task should not flush messages that were written since last flu…
  transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollStreamChannel.java
  transport-native-kqueue/src/main/java/io/netty/channel/kqueue/AbstractKQueueStreamChannel.java
  transport/src/main/java/io/netty/channel/nio/AbstractNioByteChannel.java
Labels: defect

#7765 HashedWheelTimer.newTimeout(...) may overflow
  common/src/main/java/io/netty/util/HashedWheelTimer.java
  common/src/test/java/io/netty/util/HashedWheelTimerTest.java
Labels: defect

#7782 Correctly record creation stacktrace in ResourceLeakDetector.
  common/src/main/java/io/netty/util/ResourceLeakDetector.java
Labels: defect

#7763 EmptyHeaders get with default value returns null
  codec/src/main/java/io/netty/handler/codec/EmptyHeaders.java
Labels: defect

#7806 Correctly handle non IOException during read in NioServerSocketChannel
  transport/src/main/java/io/netty/channel/nio/AbstractNioMessageChannel.java
  transport/src/main/java/io/netty/channel/socket/nio/NioServerSocketChannel.java
  transport/src/test/java/io/netty/channel/socket/nio/NioServerSocketChannelTest.java
Labels: defect

#7807 HttpServerUpgradeHandler shouldn't wait for flush to reshape pipeline
  codec-http/src/main/java/io/netty/handler/codec/http/HttpServerUpgradeHandler.java
  codec-http/src/test/java/io/netty/handler/codec/http/HttpServerUpgradeHandlerTest.java
  codec-http2/src/test/java/io/netty/handler/codec/http2/CleartextHttp2ServerUpgradeHandlerTest.java
Labels: defect

#7801 NIO read spin event loop spin when half closed
  testsuite/src/main/java/io/netty/testsuite/transport/socket/SocketHalfClosedTest.java
  transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollChannel.java
  transport-native-kqueue/src/main/java/io/netty/channel/kqueue/AbstractKQueueChannel.java
  transport/src/main/java/io/netty/channel/nio/AbstractNioByteChannel.java
  transport/src/main/java/io/netty/channel/oio/AbstractOioByteChannel.java
Labels: defect

#7813 Limit the number of bytes to use to copy the content of a direct buff…
  buffer/src/main/java/io/netty/buffer/ByteBufUtil.java
  buffer/src/main/java/io/netty/buffer/PooledDirectByteBuf.java
  buffer/src/main/java/io/netty/buffer/UnpooledDirectByteBuf.java
  buffer/src/main/java/io/netty/buffer/UnsafeByteBufUtil.java
Labels: improvement

#7803 Add DnsNameResolver.resolveAll(DnsQuestion)
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsAddressDecoder.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsAddressResolveContext.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsRecordResolveContext.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsResolveContext.java
  resolver-dns/src/test/java/io/netty/resolver/dns/DnsNameResolverTest.java
Labels: feature
