Repository netty/netty, pull requests merged in 2018-09, with the labels that each got.

#8257 Correctly reset offset when fail lazy because of too long frame.
  codec/src/main/java/io/netty/handler/codec/LineBasedFrameDecoder.java
  codec/src/test/java/io/netty/handler/codec/LineBasedFrameDecoderTest.java
Labels: defect

#8266 Use a non-volatile read for ensureAccessible() whenever possible to r…
  buffer/src/main/java/io/netty/buffer/AbstractByteBuf.java
  buffer/src/main/java/io/netty/buffer/AbstractReferenceCountedByteBuf.java
  buffer/src/main/java/io/netty/buffer/WrappedCompositeByteBuf.java
  microbench/src/main/java/io/netty/microbench/buffer/UnsafeByteBufBenchmark.java
Labels: discussion, improvement

#8268 Allow to configure socket option SO_BUSY_POLL
  transport-native-epoll/src/main/c/netty_epoll_linuxsocket.c
  transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollChannelOption.java
  transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollSocketChannelConfig.java
  transport-native-epoll/src/main/java/io/netty/channel/epoll/LinuxSocket.java
Labels: feature, improvement

#7816 Don't re-arm timerfd each epoll_wait
  common/src/main/java/io/netty/util/concurrent/SingleThreadEventExecutor.java
  transport-native-epoll/src/main/c/netty_epoll_native.c
  transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollEventLoop.java
Labels: improvement

#8292 Fix incorrectly encoded empty SOCKS5 address
  codec-socks/src/main/java/io/netty/handler/codec/socksx/v5/Socks5AddressEncoder.java
  codec-socks/src/test/java/io/netty/handler/codec/socksx/v5/DefaultSocks5CommandResponseTest.java
Labels: defect

#8305 Ensure we always encode all data in JdkZlibEncoder.
  codec/src/main/java/io/netty/handler/codec/compression/JdkZlibEncoder.java
Labels: defect

#8319 Fixed illegal reflective access by not relying on a sun.net.dns class. (#8318)
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java
  resolver-dns/src/main/java/io/netty/resolver/dns/UnixResolverDnsServerAddressStreamProvider.java
  resolver-dns/src/test/java/io/netty/resolver/dns/UnixResolverDnsServerAddressStreamProviderTest.java
Labels: cleanup, defect, improvement

#8325 Ensure ByteToMessageDecoder.Cumulator implementations always release …
  codec/src/main/java/io/netty/handler/codec/ByteToMessageDecoder.java
  codec/src/test/java/io/netty/handler/codec/ByteToMessageDecoderTest.java
Labels: defect

#8316 Use AuthoritativeDnsServerCache for creating the new redirect stream.
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java
Labels: improvement

#8333 Check if hostname validation is supported before trying to use in test.
  handler/src/test/java/io/netty/handler/ssl/SSLEngineTest.java
Labels: cleanup

#8283 Ensure X509KeyManager methods are called on the correct time when using server-side and support more methods of ExtendedSSLSession.
  handler/src/main/java/io/netty/handler/ssl/ExtendedOpenSslSession.java
  handler/src/main/java/io/netty/handler/ssl/Java8SslUtils.java
  handler/src/main/java/io/netty/handler/ssl/OpenSslClientContext.java
  handler/src/main/java/io/netty/handler/ssl/OpenSslKeyMaterialManager.java
  handler/src/main/java/io/netty/handler/ssl/OpenSslServerContext.java
  handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslClientContext.java
  handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslContext.java
  handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslEngine.java
  handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslServerContext.java
  handler/src/main/java/io/netty/handler/ssl/SignatureAlgorithmConverter.java
  handler/src/test/java/io/netty/handler/ssl/OpenSslTestUtils.java
  handler/src/test/java/io/netty/handler/ssl/SignatureAlgorithmConverterTest.java
  handler/src/test/java/io/netty/handler/ssl/SniClientJava8TestUtil.java
  handler/src/test/java/io/netty/handler/ssl/SniClientTest.java
  handler/src/test/java/io/netty/handler/ssl/SslErrorTest.java
  pom.xml
Labels: defect, feature, improvement

#8335 Avoid repeating the same field and hiding it
  transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollChannelConfig.java
  transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollDatagramChannelConfig.java
  transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollServerChannelConfig.java
  transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollServerSocketChannelConfig.java
  transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollSocketChannelConfig.java
  transport-native-kqueue/src/main/java/io/netty/channel/kqueue/KQueueChannelConfig.java
  transport-native-kqueue/src/main/java/io/netty/channel/kqueue/KQueueDatagramChannelConfig.java
  transport-native-kqueue/src/main/java/io/netty/channel/kqueue/KQueueServerChannelConfig.java
  transport-native-kqueue/src/main/java/io/netty/channel/kqueue/KQueueServerSocketChannelConfig.java
  transport-native-kqueue/src/main/java/io/netty/channel/kqueue/KQueueSocketChannelConfig.java
Labels: cleanup

#8267 Added option to do busy-wait on epoll
  transport-native-epoll/src/main/c/netty_epoll_native.c
  transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollEventLoop.java
  transport-native-epoll/src/main/java/io/netty/channel/epoll/Native.java
  transport-native-epoll/src/test/java/io/netty/channel/epoll/EpollETSocketStringEchoBusyWaitTest.java
  transport-native-epoll/src/test/java/io/netty/channel/epoll/EpollLTSocketStringEchoBusyWaitTest.java
  transport-native-epoll/src/test/java/io/netty/channel/epoll/EpollSocketStringEchoBusyWaitTest.java
  transport-native-kqueue/src/main/java/io/netty/channel/kqueue/KQueueEventLoop.java
  transport/src/main/java/io/netty/channel/SelectStrategy.java
  transport/src/main/java/io/netty/channel/nio/NioEventLoop.java
Labels: feature
