Repository netty/netty, pull requests merged in 2018-06, with the labels that each got.

#8009 Remove dead code in Http2CodecUtil
  codec-http2/src/main/java/io/netty/handler/codec/http2/Http2CodecUtil.java
Labels: cleanup

#8021 Defer channelInactive and channelUnregistered events in Http2MultiplexCodec
  codec-http2/src/main/java/io/netty/handler/codec/http2/Http2MultiplexCodec.java
  codec-http2/src/test/java/io/netty/handler/codec/http2/Http2MultiplexCodecTest.java
Labels: defect

#8035 Revert "Ignore some test-flakiness when using Java11+ due outstanding…
  testsuite/src/main/java/io/netty/testsuite/transport/socket/SocketHalfClosedTest.java
Labels: cleanup

#8033 Remove some cipher protocol combos for tests due removal in more rece…
  handler/src/test/java/io/netty/handler/ssl/OpenSslEngineTest.java
Labels: cleanup

#8048 Fix random number generator in WebSocketUtil
  codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketUtil.java
  codec-http/src/test/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshakerTest.java
  codec-http/src/test/java/io/netty/handler/codec/http/websocketx/WebSocketUtilTest.java
Labels: defect

#8054 Get rid of deprecated SslContext methods in handler-proxy tests
  handler-proxy/src/test/java/io/netty/handler/proxy/ProxyHandlerTest.java
Labels: cleanup

#8058 Remove id from DnsQueryContextManager whenever the promise is fullfil…
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsQueryContext.java
Labels: defect

#8062 Store NativeDatagramPacketArray directly in the EpollEventLoop
  transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollStreamChannel.java
  transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollDatagramChannel.java
  transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollEventLoop.java
  transport-native-epoll/src/main/java/io/netty/channel/epoll/NativeDatagramPacketArray.java
Labels: improvement

#8050 OpenSSL (and so netty-tcnative) should allow to use custom engine.
  handler/src/main/java/io/netty/handler/ssl/OpenSsl.java
Labels: feature

#8075 Replace toArray(new T[size]) with toArray(new T[0]) to eliminate zero…
  buffer/src/main/java/io/netty/buffer/CompositeByteBuf.java
  buffer/src/main/java/io/netty/buffer/FixedCompositeByteBuf.java
  buffer/src/test/java/io/netty/buffer/AbstractCompositeByteBufTest.java
  codec-http/src/main/java/io/netty/handler/codec/http/cookie/ClientCookieEncoder.java
  codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java
  codec-http/src/test/java/io/netty/handler/codec/http/DefaultHttpHeadersTest.java
  common/src/main/java/io/netty/util/AsciiString.java
  common/src/main/java/io/netty/util/concurrent/AbstractScheduledEventExecutor.java
  common/src/main/java/io/netty/util/concurrent/FastThreadLocal.java
  common/src/test/java/io/netty/util/ConstantPoolTest.java
  handler/src/main/java/io/netty/handler/ssl/ConscryptAlpnSslEngine.java
  handler/src/main/java/io/netty/handler/ssl/IdentityCipherSuiteFilter.java
  handler/src/main/java/io/netty/handler/ssl/JdkSslContext.java
  handler/src/main/java/io/netty/handler/ssl/OpenSsl.java
  handler/src/main/java/io/netty/handler/ssl/PemReader.java
  handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslClientContext.java
  handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslContext.java
  handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslEngine.java
  handler/src/main/java/io/netty/handler/ssl/SupportedCipherSuiteFilter.java
  handler/src/main/java/io/netty/handler/ssl/util/FingerprintTrustManagerFactory.java
  handler/src/test/java/io/netty/handler/ssl/OpenSslEngineTest.java
  microbench/src/main/java/io/netty/microbench/util/AbstractMicrobenchmarkBase.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DefaultDnsServerAddressStreamProvider.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolverBuilder.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsServerAddresses.java
  resolver-dns/src/test/java/io/netty/resolver/dns/TestDnsServer.java
  resolver/src/main/java/io/netty/resolver/AddressResolverGroup.java
  transport-udt/src/test/java/io/netty/test/udt/util/CaliperMeasure.java
  transport/src/main/java/io/netty/bootstrap/ServerBootstrap.java
Labels: improvement
