Repository netty/netty, pull requests merged in 2018-04, with the labels that each got.

#7824 Don't replace all connection headers when sending h2c upgrade request
  codec-http/src/main/java/io/netty/handler/codec/http/HttpClientUpgradeHandler.java
  codec-http/src/test/java/io/netty/handler/codec/http/HttpClientUpgradeHandlerTest.java
Labels: defect

#7839 CorsHandler.write(...) should not cause a flush.
  codec-http/src/main/java/io/netty/handler/codec/http/cors/CorsHandler.java
Labels: defect

#7841 add task before starting thread in SingleThreadEventExecutor.execute
  common/src/main/java/io/netty/util/concurrent/SingleThreadEventExecutor.java
Labels: improvement

#7821 Better handling of streaming JSON data in JsonObjectDecoder
  codec/src/main/java/io/netty/handler/codec/json/JsonObjectDecoder.java
  codec/src/test/java/io/netty/handler/codec/json/JsonObjectDecoderTest.java
Labels: defect

#7866 AsciiString#indexOf out of bounds
  common/src/main/java/io/netty/util/AsciiString.java
  common/src/test/java/io/netty/util/AsciiStringCharacterTest.java
Labels: defect

#7874 Only reset readIsPending if outboundBuffer is not empty.
  transport/src/main/java/io/netty/channel/local/LocalChannel.java
  transport/src/test/java/io/netty/channel/local/LocalChannelTest.java
Labels: defect

#7884 Update os-maven-plugin to 1.6.0
  pom.xml
Labels: cleanup

#7402 EventLoop.schedule with big delay fails
  common/src/main/java/io/netty/util/concurrent/AbstractScheduledEventExecutor.java
  transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollEventLoop.java
  transport-native-epoll/src/test/java/io/netty/channel/epoll/EpollEventLoopTest.java
  transport-native-kqueue/src/main/java/io/netty/channel/kqueue/KQueueEventLoop.java
  transport-native-kqueue/src/test/java/io/netty/channel/kqueue/KQueueEventLoopTest.java
  transport/src/main/java/io/netty/channel/nio/NioEventLoop.java
  transport/src/test/java/io/netty/channel/nio/NioEventLoopTest.java
Labels: defect

#7885 Respect MAX_MESSAGES_PER_READ in LocalChannel / LocalServerChannel.
  transport/src/main/java/io/netty/channel/local/LocalChannel.java
  transport/src/main/java/io/netty/channel/local/LocalServerChannel.java
  transport/src/test/java/io/netty/channel/local/LocalChannelTest.java
Labels: defect

#7894 Fix IllegalReferenceCountException when using Http2MultiplexCodec and…
  codec-http2/src/main/java/io/netty/handler/codec/http2/Http2MultiplexCodec.java
  codec-http2/src/test/java/io/netty/handler/codec/http2/Http2MultiplexCodecTest.java
Labels: defect
