Repository netty/netty, pull requests merged in 2018-11, with the labels that each got.

#8452 PlatformDependent.maxDirectMemory() must respect io.netty.maxDirectMe…
  common/src/main/java/io/netty/util/internal/PlatformDependent.java
Labels: defect

#8322 Make it clear that HashedWheelTimer only support millis.
  common/src/main/java/io/netty/util/HashedWheelTimer.java
Labels: cleanup

#8467 Replace ConcurrentHashMap at allLeaks with a thread-safe set
  common/src/main/java/io/netty/util/ResourceLeakDetector.java
Labels: cleanup

#8497 Fix ref-counting when CompositeByteBuf is used with retainedSlice()
  buffer/src/main/java/io/netty/buffer/CompositeByteBuf.java
  buffer/src/test/java/io/netty/buffer/AbstractCompositeByteBufTest.java
Labels: defect

#8555 Cleanup SslHandler handshake/renegotiation
  handler/src/main/java/io/netty/handler/ssl/SslHandler.java
Labels: cleanup

#8485 Correctly convert between openssl / boringssl and java cipher names w…
  handler/src/main/java/io/netty/handler/ssl/CipherSuiteConverter.java
  handler/src/main/java/io/netty/handler/ssl/OpenSsl.java
  handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslContext.java
  handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslEngine.java
  handler/src/main/java/io/netty/handler/ssl/SslUtils.java
  handler/src/test/java/io/netty/handler/ssl/CipherSuiteConverterTest.java
  handler/src/test/java/io/netty/handler/ssl/SSLEngineTest.java
Labels: defect

#8560 ReferenceCountedOpenSslEngine SSLSession.getLocalCertificates() / get…
  handler/src/main/java/io/netty/handler/ssl/DefaultOpenSslKeyMaterial.java
  handler/src/main/java/io/netty/handler/ssl/OpenSslKeyMaterial.java
  handler/src/main/java/io/netty/handler/ssl/OpenSslKeyMaterialManager.java
  handler/src/main/java/io/netty/handler/ssl/OpenSslKeyMaterialProvider.java
  handler/src/main/java/io/netty/handler/ssl/OpenSslPrivateKey.java
  handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslEngine.java
  handler/src/test/java/io/netty/handler/ssl/OpenSslEngineTest.java
  handler/src/test/java/io/netty/handler/ssl/SSLEngineTest.java
Labels: defect

#8564 Swallow SSL Exception "closing inbound before receiving peer's close_notify" when running on Java 11 (#8463)
  handler/src/main/java/io/netty/handler/ssl/SslHandler.java
Labels: cleanup, improvement

#8568 Allow adjusting of lead detection sampling interval.
  common/src/main/java/io/netty/util/ResourceLeakDetector.java
  common/src/main/java/io/netty/util/ResourceLeakDetectorFactory.java
Labels: feature, improvement

#8582 Remove transitive dependency on slf4j in example
  example/src/main/java/io/netty/example/http/websocketx/server/WebSocketFrameHandler.java
Labels: cleanup

#8470 Combine flushes in DnsNameResolver to allow usage of sendmmsg to redu…
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsQueryContext.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsResolveContext.java
Labels: feature, improvement

#8591 Remove @Deprecated from package-info.java file
  transport-sctp/src/main/java/io/netty/channel/sctp/oio/package-info.java
  transport/src/main/java/io/netty/channel/oio/package-info.java
  transport/src/main/java/io/netty/channel/socket/oio/package-info.java
Labels: cleanup

#8592 HeadContext is inbound and outbound
  transport/src/main/java/io/netty/channel/DefaultChannelPipeline.java
Labels: cleanup, defect

#8596 Use addAndGet(...) as a replacement for compareAndSet(...) when track…
  common/src/main/java/io/netty/util/internal/PlatformDependent.java
Labels: improvement

#8597 Change offset calculating formula to
  buffer/src/main/java/io/netty/buffer/PoolArena.java
  buffer/src/test/java/io/netty/buffer/PoolArenaTest.java
Labels: defect

#8600 Move less common code-path to extra method to allow inlining of write…
  buffer/src/main/java/io/netty/buffer/ByteBufUtil.java
Labels: improvement

#8583 Harden ref-counting concurrency semantics
  buffer/src/main/java/io/netty/buffer/AbstractReferenceCountedByteBuf.java
  common/src/main/java/io/netty/util/AbstractReferenceCounted.java
  common/src/test/java/io/netty/util/AbstractReferenceCountedTest.java
Labels: defect

#8598 Reduce http2 buffer slicing
  codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2FrameReader.java
  codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2FrameWriter.java
Labels: cleanup, improvement
