Repository netty/netty, pull requests merged in 2018-10, with the labels that each got.

#8349 Correctly decrement pending bytes when submitting AbstractWriteTask f…
  transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java
  transport/src/test/java/io/netty/channel/ChannelOutboundBufferTest.java
Labels: defect

#8351 Correctly parse /etc/resolv.conf when contain multiple entries for se…
  resolver-dns/src/main/java/io/netty/resolver/dns/UnixResolverDnsServerAddressStreamProvider.java
  resolver-dns/src/test/java/io/netty/resolver/dns/UnixResolverDnsServerAddressStreamProviderTest.java
Labels: defect

#8350 epoll_wait produces an EINVAL error since 4.1.30
  transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollEventLoop.java
  transport-native-epoll/src/test/java/io/netty/channel/epoll/EpollEventLoopTest.java
Labels: defect

#8378 Prevent NPE when attempting to set client key material with no alias
  handler/src/main/java/io/netty/handler/ssl/OpenSslKeyMaterialManager.java
  handler/src/test/java/io/netty/handler/ssl/OpenSslKeyMaterialManagerTest.java
Labels: defect

#8293 Add support for TLSv1.3
  handler/src/main/java/io/netty/handler/ssl/CipherSuiteConverter.java
  handler/src/main/java/io/netty/handler/ssl/JdkSslContext.java
  handler/src/main/java/io/netty/handler/ssl/OpenSsl.java
  handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslClientContext.java
  handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslContext.java
  handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslEngine.java
  handler/src/main/java/io/netty/handler/ssl/SslUtils.java
  handler/src/test/java/io/netty/handler/ssl/CipherSuiteCanaryTest.java
  handler/src/test/java/io/netty/handler/ssl/CipherSuiteConverterTest.java
  handler/src/test/java/io/netty/handler/ssl/ConscryptJdkSslEngineInteropTest.java
  handler/src/test/java/io/netty/handler/ssl/ConscryptSslEngineTest.java
  handler/src/test/java/io/netty/handler/ssl/JdkConscryptSslEngineInteropTest.java
  handler/src/test/java/io/netty/handler/ssl/JdkOpenSslEngineInteroptTest.java
  handler/src/test/java/io/netty/handler/ssl/JdkSslEngineTest.java
  handler/src/test/java/io/netty/handler/ssl/OpenSslEngineTest.java
  handler/src/test/java/io/netty/handler/ssl/OpenSslJdkSslEngineInteroptTest.java
  handler/src/test/java/io/netty/handler/ssl/OpenSslTestUtils.java
  handler/src/test/java/io/netty/handler/ssl/ParameterizedSslHandlerTest.java
  handler/src/test/java/io/netty/handler/ssl/ReferenceCountedOpenSslEngineTest.java
  handler/src/test/java/io/netty/handler/ssl/SSLEngineTest.java
  handler/src/test/java/io/netty/handler/ssl/SslContextBuilderTest.java
  handler/src/test/java/io/netty/handler/ssl/SslErrorTest.java
  handler/src/test/java/io/netty/handler/ssl/SslUtilsTest.java
  pom.xml
  testsuite/src/main/java/io/netty/testsuite/transport/socket/SocketSslClientRenegotiateTest.java
  testsuite/src/main/java/io/netty/testsuite/transport/socket/SocketSslEchoTest.java
  testsuite/src/main/java/io/netty/testsuite/transport/socket/SocketSslSessionReuseTest.java
Labels: feature, improvement

#8399 Ensure OpenSslEngine will not try to call SSL_free multiple times eve…
  handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslEngine.java
Labels: defect

#8395 Fix context and window sizes sides.
  codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/PerMessageDeflateClientExtensionHandshaker.java
  codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/PerMessageDeflateServerExtensionHandshaker.java
  codec-http/src/test/java/io/netty/handler/codec/http/websocketx/extensions/compression/PerFrameDeflateDecoderTest.java
  codec-http/src/test/java/io/netty/handler/codec/http/websocketx/extensions/compression/PerMessageDeflateClientExtensionHandshakerTest.java
Labels: defect

#8403 CompositeByteBuf.decompose(...) does not correctly slice content.
  buffer/src/main/java/io/netty/buffer/CompositeByteBuf.java
  buffer/src/test/java/io/netty/buffer/AbstractCompositeByteBufTest.java
Labels: defect

#8416 Upgrade commons-compress to 2.0.18
  pom.xml
Labels: cleanup

#8415 Correctly detect if KeyManagerFactory is supported by OpenSSL even wh…
  handler/src/main/java/io/netty/handler/ssl/OpenSsl.java
Labels: defect

#8410 (fix) incorrect reachability assumption in ResourceLeakDetector
  common/src/main/java/io/netty/util/ResourceLeakDetector.java
Labels: defect

#8392 Optimize AbstractByteBuf.getCharSequence() in US_ASCII case
  buffer/src/main/java/io/netty/buffer/AbstractByteBuf.java
  buffer/src/test/java/io/netty/buffer/AbstractByteBufTest.java
  codec-socks/src/test/java/io/netty/handler/codec/socks/SocksCmdRequestTest.java
  codec-socks/src/test/java/io/netty/handler/codec/socks/SocksCmdResponseTest.java
  codec/src/test/java/io/netty/handler/codec/compression/SnappyTest.java
  microbench/src/main/java/io/netty/buffer/AbstractByteBufGetCharSequenceBenchmark.java
Labels: improvement

#8393 Exploit PlatformDependent.allocateUninitializedArray() in more places
  buffer/src/main/java/io/netty/buffer/ByteBufUtil.java
  buffer/src/main/java/io/netty/buffer/PooledDirectByteBuf.java
  buffer/src/main/java/io/netty/buffer/ReadOnlyByteBufferBuf.java
  buffer/src/main/java/io/netty/buffer/Unpooled.java
  buffer/src/main/java/io/netty/buffer/UnpooledDirectByteBuf.java
  buffer/src/main/java/io/netty/buffer/UnpooledHeapByteBuf.java
  buffer/src/main/java/io/netty/buffer/UnsafeByteBufUtil.java
  codec/src/main/java/io/netty/handler/codec/bytes/ByteArrayDecoder.java
  codec/src/main/java/io/netty/handler/codec/protobuf/ProtobufDecoder.java
  codec/src/main/java/io/netty/handler/codec/protobuf/ProtobufDecoderNano.java
  common/src/main/java/io/netty/util/AsciiString.java
  transport/src/main/java/io/netty/channel/socket/oio/OioDatagramChannel.java
Labels: improvement

#8438 Fix leak and corruption bugs in CompositeByteBuf
  buffer/src/main/java/io/netty/buffer/CompositeByteBuf.java
  buffer/src/test/java/io/netty/buffer/AbstractCompositeByteBufTest.java
Labels: defect

#8435 Correctly init X509Certificate array when testing if we need to wrap …
  handler/src/main/java/io/netty/handler/ssl/OpenSsl.java
  handler/src/main/java/io/netty/handler/ssl/OpenSslTlsv13X509ExtendedTrustManager.java
Labels: cleanup

#8441 Remove uninterpolated `{}` in DefaultHttp2ConnectionDecoder log message
  codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionDecoder.java
Labels: cleanup

#8420 Avoid allocations when wrapping byte[] and ByteBuffer arrays as ByteBuf
  buffer/src/main/java/io/netty/buffer/CompositeByteBuf.java
  buffer/src/main/java/io/netty/buffer/Unpooled.java
Labels: improvement
