Repository netty/netty, pull requests merged in 2018-07, with the labels that each got.

#8091 Fix support for shading native libraries which was broken in b818852c…
  transport-native-unix-common/src/main/c/netty_unix_socket.c
Labels: defect

#8118 Double 'should' word in docs of continueReading() method
  transport/src/main/java/io/netty/channel/RecvByteBufAllocator.java
Labels: cleanup, documentation

#8109 Auto-detect Log4J2 for logging if on the class-path
  common/src/main/java/io/netty/util/internal/logging/InternalLoggerFactory.java
Labels: defect

#8116 Fix length calculation in AsciiString.indexOf(...) and so eliminate A…
  common/src/main/java/io/netty/util/AsciiString.java
  common/src/test/java/io/netty/util/AsciiStringCharacterTest.java
Labels: defect

#8126 Fix possible NPE introduced by a137291ad161c970259d9a5d7cc206c026f08e…
  handler/src/main/java/io/netty/handler/ssl/OpenSslX509KeyManagerFactory.java
  handler/src/test/java/io/netty/handler/ssl/OpenSslCachingKeyMaterialProviderTest.java
  handler/src/test/java/io/netty/handler/ssl/OpenSslKeyMaterialProviderTest.java
  handler/src/test/java/io/netty/handler/ssl/OpenSslX509KeyManagerFactoryProviderTest.java
Labels: defect

#8085 Support the usage of SocketOption when nio is used and the java versi…
  pom.xml
  transport/src/main/java/io/netty/channel/socket/nio/NioChannelOption.java
  transport/src/main/java/io/netty/channel/socket/nio/NioDatagramChannelConfig.java
  transport/src/main/java/io/netty/channel/socket/nio/NioServerSocketChannel.java
  transport/src/main/java/io/netty/channel/socket/nio/NioSocketChannel.java
  transport/src/test/java/io/netty/channel/socket/nio/AbstractNioChannelTest.java
  transport/src/test/java/io/netty/channel/socket/nio/NioDatagramChannelTest.java
  transport/src/test/java/io/netty/channel/socket/nio/NioServerSocketChannelTest.java
  transport/src/test/java/io/netty/channel/socket/nio/NioSocketChannelTest.java
Labels: feature, improvement

#8154 DefaultPromise.getNow() does not correctly handle DefaultPromise.setU…
  common/src/main/java/io/netty/util/concurrent/DefaultPromise.java
  common/src/test/java/io/netty/util/concurrent/DefaultPromiseTest.java
Labels: defect

#8153 Leak detection combined with composite buffers results in incorrectly…
  buffer/src/main/java/io/netty/buffer/ByteBufUtil.java
  buffer/src/test/java/io/netty/buffer/ByteBufUtilTest.java
Labels: defect

#8147 HTTP/2 child channel read cycle doesn't respect RecvByteBufAllocator and
  codec-http2/src/main/java/io/netty/handler/codec/http2/Http2MultiplexCodec.java
  codec-http2/src/test/java/io/netty/handler/codec/http2/Http2MultiplexCodecTest.java
  codec-http2/src/test/java/io/netty/handler/codec/http2/LastInboundHandler.java
  codec-http2/src/test/java/io/netty/handler/codec/http2/TestChannelInitializer.java
Labels: defect

#8160 Lazily initialize NativeDatagramPacketArray and IovArray in EpollEventLoop
  transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollEventLoop.java
  transport-native-epoll/src/main/java/io/netty/channel/epoll/NativeDatagramPacketArray.java
Labels: defect, improvement
