Repository netty/netty, pull requests merged in 2018-08, with the labels that each got.

#8168 Ensure NIO transport can be used on Java6 again.
  transport/src/main/java/io/netty/channel/socket/nio/NioChannelOption.java
Labels: defect

#8176 CompositeByteBuf nioBuffer doesn't always alloc
  buffer/src/main/java/io/netty/buffer/CompositeByteBuf.java
Labels: improvement

#8183 Workaround JDK bug that will cause an AssertionError when calling Ser…
  pom.xml
  transport/src/main/java/io/netty/channel/socket/nio/NioChannelOption.java
  transport/src/test/java/io/netty/channel/socket/nio/AbstractNioChannelTest.java
Labels: defect

#8178 Set initial SNI hostname when creating an OpenSSL engine in client mode
  handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslEngine.java
  handler/src/main/java/io/netty/handler/ssl/SslUtils.java
  handler/src/test/java/io/netty/handler/ssl/SSLEngineTest.java
Labels: defect

#8181 Correctly handle hostnames with and without trailing dot in the DefaultDnsCache and use it for searchdomains.
  resolver-dns/src/main/java/io/netty/resolver/dns/DefaultDnsCache.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsAddressResolveContext.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsResolveContext.java
  resolver-dns/src/test/java/io/netty/resolver/dns/DefaultDnsCacheTest.java
  resolver-dns/src/test/java/io/netty/resolver/dns/DnsNameResolverTest.java
Labels: defect

#8207 Ensure multiple shaded version of the same netty artifact can be load…
  testsuite-shading/pom.xml
  testsuite-shading/src/test/java/io/netty/testsuite/shading/ShadingIT.java
  transport-native-epoll/pom.xml
  transport-native-epoll/src/main/c/netty_epoll_native.c
  transport-native-kqueue/pom.xml
  transport-native-kqueue/src/main/c/netty_kqueue_eventarray.c
  transport-native-kqueue/src/main/c/netty_kqueue_native.c
  transport-native-unix-common/pom.xml
Labels: defect, improvement

#8177 Correctly handle DNS redirects for NS servers that have no ADDITIONAL…
  resolver-dns/src/main/java/io/netty/resolver/dns/AuthoritativeDnsServerCache.java
  resolver-dns/src/main/java/io/netty/resolver/dns/AuthoritativeDnsServerCacheAdapter.java
  resolver-dns/src/main/java/io/netty/resolver/dns/Cache.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DefaultAuthoritativeDnsServerCache.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DefaultDnsCache.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DefaultDnsServerAddressStreamProvider.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DefaultDnsServerAddresses.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsAddressResolveContext.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolverBuilder.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsResolveContext.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsServerAddresses.java
  resolver-dns/src/main/java/io/netty/resolver/dns/NameServerComparator.java
  resolver-dns/src/main/java/io/netty/resolver/dns/NoopAuthoritativeDnsServerCache.java
  resolver-dns/src/main/java/io/netty/resolver/dns/RotationalDnsServerAddresses.java
  resolver-dns/src/main/java/io/netty/resolver/dns/SequentialDnsServerAddressStream.java
  resolver-dns/src/main/java/io/netty/resolver/dns/ShuffledDnsServerAddressStream.java
  resolver-dns/src/test/java/io/netty/resolver/dns/DefaultAuthoritativeDnsServerCacheTest.java
  resolver-dns/src/test/java/io/netty/resolver/dns/DnsNameResolverTest.java
  resolver-dns/src/test/java/io/netty/resolver/dns/NameServerComparatorTest.java
  resolver-dns/src/test/java/io/netty/resolver/dns/TestDnsServer.java
Labels: defect

#8211 Allow to parse hosts file which is stored in a different encoding the…
  resolver/src/main/java/io/netty/resolver/DefaultHostsFileEntriesResolver.java
  resolver/src/main/java/io/netty/resolver/HostsFileParser.java
  resolver/src/test/java/io/netty/resolver/HostsFileParserTest.java
  resolver/src/test/resources/io/netty/resolver/hosts-unicode
Labels: improvement

#8226 Clarify deprecation docs a bit.
  transport/src/main/java/io/netty/channel/ChannelConfig.java
  transport/src/main/java/io/netty/channel/ChannelOption.java
Labels: documentation

#8204 CleanerJava9 should be able to do its job even with a SecurityManager…
  common/src/main/java/io/netty/util/internal/CleanerJava9.java
Labels: defect

#8232 Fix race condition in the NonStickyEventExecutorGroup
  common/src/main/java/io/netty/util/concurrent/NonStickyEventExecutorGroup.java
  common/src/test/java/io/netty/util/concurrent/NonStickyEventExecutorGroupTest.java
Labels: defect

#8234 We should be able to use the ByteBuffer cleaner on java8 (and earlier…
  common/src/main/java/io/netty/util/internal/CleanerJava6.java
  common/src/main/java/io/netty/util/internal/PlatformDependent.java
Labels: improvement

#8219 Add headers to MqttMessage returned by MqttDecoder in case of DecoderException
  codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttDecoder.java
  codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttMessageFactory.java
  codec-mqtt/src/test/java/io/netty/handler/codec/mqtt/MqttCodecTest.java
Labels: improvement
