Repository netty/netty, pull requests merged in 2018-05, with the labels that each got.

#7899 Add null-check to Htt2FrameCodec#consumeBytes.
  codec-http2/src/main/java/io/netty/handler/codec/http2/Http2FrameCodec.java
  codec-http2/src/test/java/io/netty/handler/codec/http2/Http2FrameCodecTest.java
Labels: defect

#7906 DefaultDnsCache should store more then one Entry per hostname.
  resolver-dns/src/main/java/io/netty/resolver/dns/DefaultDnsCache.java
  resolver-dns/src/test/java/io/netty/resolver/dns/DefaultDnsCacheTest.java
Labels: defect

#7918 Fix tiny typo in FixedChannelPool error message
  transport/src/main/java/io/netty/channel/pool/FixedChannelPool.java
Labels: cleanup

#7921 Fix the error message in ReferenceCounted.release
  buffer/src/main/java/io/netty/buffer/AbstractReferenceCountedByteBuf.java
  buffer/src/test/java/io/netty/buffer/AbstractReferenceCountedByteBufTest.java
  common/src/main/java/io/netty/util/AbstractReferenceCounted.java
  common/src/test/java/io/netty/util/AbstractReferenceCountedTest.java
Labels: cleanup

#7920 Enfore upper limit for minTtl when using DefaultCacheEntry.
  resolver-dns/src/main/java/io/netty/resolver/dns/DefaultDnsCache.java
  resolver-dns/src/test/java/io/netty/resolver/dns/DefaultDnsCacheTest.java
Labels: defect

#7919 Always follow cnames even if a matching A or AAAA record was found.
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsAddressResolveContext.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsRecordResolveContext.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsResolveContext.java
  resolver-dns/src/test/java/io/netty/resolver/dns/DnsNameResolverTest.java
Labels: defect

#7923 Make osgi testing work with java>=9 by updating to felix 5.6.10
  pom.xml
  testsuite-osgi/pom.xml
Labels: cleanup, improvement

#7934 Update the comment of io.netty.buffer.PoolChunk.java
  buffer/src/main/java/io/netty/buffer/PoolChunk.java
Labels: cleanup, documentation

#7937 Avoid implicit allocations in Http2FrameLogger when logging is disabled
  codec-http2/src/main/java/io/netty/handler/codec/http2/Http2FrameLogger.java
Labels: improvement

#7943 Verify error stack is empty after each operation when using Reference…
  handler/src/test/java/io/netty/handler/ssl/Java8SslTestUtils.java
  handler/src/test/java/io/netty/handler/ssl/JdkOpenSslEngineInteroptTest.java
  handler/src/test/java/io/netty/handler/ssl/OpenSslEngineTest.java
  handler/src/test/java/io/netty/handler/ssl/OpenSslErrorStackAssertSSLEngine.java
  handler/src/test/java/io/netty/handler/ssl/OpenSslJdkSslEngineInteroptTest.java
  handler/src/test/java/io/netty/handler/ssl/SSLEngineTest.java
Labels: improvement

#7945 Correctly calculate and respect if we can correctly fullfil wrap for …
  handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslEngine.java
  handler/src/test/java/io/netty/handler/ssl/OpenSslEngineTest.java
Labels: defect

#7955 Propagate pong frames in WebSocketProtocolHandler
  codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientProtocolHandler.java
  codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketProtocolHandler.java
  codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketServerProtocolHandler.java
  codec-http/src/test/java/io/netty/handler/codec/http/websocketx/WebSocketProtocolHandlerTest.java
Labels: feature, improvement

#7966 Don't use VM.maxDirectMemory() on IBM J9 / Eclipse OpenJ9 to retrieve…
  common/src/main/java/io/netty/util/internal/PlatformDependent.java
Labels: defect

#7976 Correctly let Http2UnkownFrame extend HttpStreamFrame and so be usabl…
  codec-http2/src/main/java/io/netty/handler/codec/http2/Http2UnknownFrame.java
  codec-http2/src/test/java/io/netty/handler/codec/http2/Http2MultiplexCodecTest.java
Labels: defect
