Repository netty/netty, pull requests merged in 2019-05, with the labels that each got.

#9114 KQueueEventLoop won't unregister active channels reusing a file descriptor
  transport-native-kqueue/src/main/java/io/netty/channel/kqueue/KQueueEventLoop.java
  transport-native-kqueue/src/test/java/io/netty/channel/kqueue/KQueueDomainSocketReuseFdTest.java
Labels: defect

#9130 Add equality check to contentEquals instance methods.
  common/src/main/java/io/netty/util/AsciiString.java
Labels: improvement

#9003 Allow to specify KeyStore type in SslContext
  example/src/main/java/io/netty/example/ocsp/OcspServerExample.java
  handler/src/main/java/io/netty/handler/ssl/JdkSslClientContext.java
  handler/src/main/java/io/netty/handler/ssl/JdkSslContext.java
  handler/src/main/java/io/netty/handler/ssl/JdkSslServerContext.java
  handler/src/main/java/io/netty/handler/ssl/OpenSslClientContext.java
  handler/src/main/java/io/netty/handler/ssl/OpenSslServerContext.java
  handler/src/main/java/io/netty/handler/ssl/OpenSslX509KeyManagerFactory.java
  handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslClientContext.java
  handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslServerContext.java
  handler/src/main/java/io/netty/handler/ssl/SslContext.java
  handler/src/main/java/io/netty/handler/ssl/SslContextBuilder.java
  handler/src/main/java/io/netty/handler/ssl/util/SelfSignedCertificate.java
  handler/src/test/java/io/netty/handler/ssl/JdkSslEngineTest.java
  handler/src/test/java/io/netty/handler/ssl/SSLEngineTest.java
  handler/src/test/java/io/netty/handler/ssl/SniClientJava8TestUtil.java
  handler/src/test/java/io/netty/handler/ssl/SniClientTest.java
  handler/src/test/java/io/netty/handler/ssl/SslContextBuilderTest.java
  handler/src/test/java/io/netty/handler/ssl/SslContextTrustManagerTest.java
Labels: feature, improvement

#9141 DnsNameResolver.resolveAll(DnsQuestion) should not try to filter dupl…
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsAddressResolveContext.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsRecordResolveContext.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsResolveContext.java
  resolver-dns/src/test/java/io/netty/resolver/dns/DnsNameResolverTest.java
Labels: defect, regression

#9125 Fix incorrect behavior of ReadOnlyByteBufferBuf.getBytes(int,ByteBuffer)
  buffer/src/main/java/io/netty/buffer/ReadOnlyByteBufferBuf.java
  buffer/src/main/java/io/netty/buffer/ReadOnlyUnsafeDirectByteBuf.java
  buffer/src/test/java/io/netty/buffer/ReadOnlyDirectByteBufferBufTest.java
Labels: defect

#9103 AsciiString.lastIndexOf(...) is implemented incorrectly
  common/src/main/java/io/netty/util/AsciiString.java
  common/src/test/java/io/netty/util/AsciiStringCharacterTest.java
Labels: defect

#9058 Ensure "full" ownership of messages passed to EmbeddedChannel.writeInbound()
  codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/DeflateDecoder.java
  codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/DeflateEncoder.java
  codec-http/src/test/java/io/netty/handler/codec/http/HttpContentDecoderTest.java
  codec-http/src/test/java/io/netty/handler/codec/http/HttpRequestDecoderTest.java
  codec-http/src/test/java/io/netty/handler/codec/http/HttpResponseDecoderTest.java
  codec-http/src/test/java/io/netty/handler/codec/http/websocketx/extensions/compression/PerFrameDeflateEncoderTest.java
  codec-http/src/test/java/io/netty/handler/codec/http/websocketx/extensions/compression/PerMessageDeflateEncoderTest.java
  codec/src/test/java/io/netty/handler/codec/ByteToMessageDecoderTest.java
  codec/src/test/java/io/netty/handler/codec/compression/ZlibTest.java
  microbench/src/main/java/io/netty/microbench/http/HttpRequestDecoderBenchmark.java
Labels: defect

#9170 Correctly detect that KeyManagerFactory is not supported when using O…
  handler/src/main/java/io/netty/handler/ssl/OpenSsl.java
Labels: defect

#9175 OpenSsl.USE_KEYMANAGER_FACTORY incorrectly set to false with BoringSSL
  handler/src/main/java/io/netty/handler/ssl/OpenSsl.java
Labels: regression

#9119 Fix redundant or missing checks and other inconsistencies in ByteBuf impls
  buffer/src/main/java/io/netty/buffer/AbstractByteBuf.java
  buffer/src/main/java/io/netty/buffer/CompositeByteBuf.java
  buffer/src/main/java/io/netty/buffer/ReadOnlyByteBufferBuf.java
  buffer/src/main/java/io/netty/buffer/UnpooledHeapByteBuf.java
Labels: cleanup
