Repository netty/netty, pull requests merged in 2019-04, with the labels that each got.

#8987 Move ChannelHandler.Skip to ChannelHandlerMask.Skip and make it packa…
  transport/src/main/java/io/netty/channel/ChannelHandler.java
  transport/src/main/java/io/netty/channel/ChannelHandlerMask.java
  transport/src/test/java/io/netty/channel/DefaultChannelPipelineTest.java
Labels: cleanup

#8985 Use SSL.setKeyMaterial(...) to test if the KeyManagerFactory is suppo…
  handler/src/main/java/io/netty/handler/ssl/OpenSsl.java
  handler/src/main/java/io/netty/handler/ssl/PemPrivateKey.java
Labels: cleanup

#9002 Http2FrameLogger should not extend ChannelHandlerAdapter
  codec-http2/src/main/java/io/netty/handler/codec/http2/Http2FrameLogger.java
Labels: cleanup

#9008 Always include initial handshake exception when throwing SslHandshake…
  handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslEngine.java
Labels: improvement

#9009 We should fail fast if the given PrivateKey or X509Certificate chain …
  handler/src/main/java/io/netty/handler/ssl/OpenSslClientContext.java
  handler/src/main/java/io/netty/handler/ssl/OpenSslKeyMaterialProvider.java
  handler/src/main/java/io/netty/handler/ssl/OpenSslServerContext.java
  handler/src/test/java/io/netty/handler/ssl/SslContextBuilderTest.java
Labels: improvement

#9006 Added UDP multicast (with caveats: no ipv6, getInterface, getNetworkI…
  transport-native-epoll/src/main/c/netty_epoll_linuxsocket.c
  transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollDatagramChannel.java
  transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollDatagramChannelConfig.java
  transport-native-epoll/src/main/java/io/netty/channel/epoll/LinuxSocket.java
  transport-native-epoll/src/test/java/io/netty/channel/epoll/EpollDatagramMulticastTest.java
Labels: feature

#8943 Allow to offload / customize key signing operations when using Boring…
  handler/src/main/java/io/netty/handler/ssl/OpenSslPrivateKeyMethod.java
  handler/src/main/java/io/netty/handler/ssl/OpenSslX509KeyManagerFactory.java
  handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslContext.java
  handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslEngine.java
  handler/src/test/java/io/netty/handler/ssl/OpenSslPrivateKeyMethodTest.java
  pom.xml
Labels: feature

#8988 Skip execution of Channel*Handler method if annotated with @Skip and …
  microbench/src/main/java/io/netty/microbench/channel/DefaultChannelPipelineBenchmark.java
  transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java
  transport/src/main/java/io/netty/channel/ChannelDuplexHandler.java
  transport/src/main/java/io/netty/channel/ChannelHandlerAdapter.java
  transport/src/main/java/io/netty/channel/ChannelHandlerMask.java
  transport/src/main/java/io/netty/channel/ChannelInboundHandlerAdapter.java
  transport/src/main/java/io/netty/channel/ChannelOutboundHandlerAdapter.java
  transport/src/main/java/io/netty/channel/DefaultChannelHandlerContext.java
  transport/src/main/java/io/netty/channel/DefaultChannelPipeline.java
  transport/src/test/java/io/netty/channel/DefaultChannelPipelineTest.java
Labels: feature, improvement

#9022 DnsNameResolver should log in trace level if notification of the prom…
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java
  resolver-dns/src/test/java/io/netty/resolver/dns/DnsNameResolverTest.java
  resolver-dns/src/test/java/io/netty/resolver/dns/TestDnsServer.java
Labels: cleanup

#9041 Make validation tools more happy by not have TrustManager impl just a…
  handler/src/main/java/io/netty/handler/ssl/OpenSslX509TrustManagerWrapper.java
Labels: cleanup

#9044 DnsNameResolver.resolveAll(...) should also contain non preferred add…
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsAddressResolveContext.java
  resolver-dns/src/main/java/io/netty/resolver/dns/PreferredAddressTypeComparator.java
  resolver-dns/src/test/java/io/netty/resolver/dns/DnsNameResolverTest.java
  resolver-dns/src/test/java/io/netty/resolver/dns/PreferredAddressTypeComparatorTest.java
Labels: defect

#9048 Use ResolvedAddressTypes.IPV4_ONLY in DnsNameResolver by default if n…
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java
Labels: defect

#9051 Correctly calculate ttl for AuthoritativeNameServer when update exist…
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsResolveContext.java
Labels: defect

#9050 DnsNameResolver.resolve(...) should notify future as soon as one pref…
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsAddressResolveContext.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsRecordResolveContext.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsResolveContext.java
  resolver-dns/src/test/java/io/netty/resolver/dns/DnsNameResolverTest.java
Labels: improvement

#9060 Have (Epoll|KQueue)RecvByteAllocatorHandle extend DelegatingHandle
  transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollRecvByteAllocatorHandle.java
  transport-native-kqueue/src/main/java/io/netty/channel/kqueue/KQueueRecvByteAllocatorHandle.java
Labels: cleanup

#9063 DefaultHeaders#valueIterator to support removal
  codec/src/main/java/io/netty/handler/codec/DefaultHeaders.java
  codec/src/test/java/io/netty/handler/codec/DefaultHeadersTest.java
Labels: improvement

#9068 Fix regression in CompositeByteBuf.discard*ReadBytes()
  buffer/src/main/java/io/netty/buffer/CompositeByteBuf.java
  buffer/src/test/java/io/netty/buffer/AbstractCompositeByteBufTest.java
Labels: defect, regression

#9066 Remove static wildcard imports in EpollDomainSocketChannelConfig
  transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollDomainSocketChannelConfig.java
Labels: cleanup

#9098 Ensure channel handler close() is not skipped in !hasDisconnect case
  transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java
  transport/src/test/java/io/netty/channel/embedded/EmbeddedChannelTest.java
Labels: defect

#9100 Throw SignatureException if OpenSslPrivateKeyMethod.* return null to …
  handler/src/main/java/io/netty/handler/ssl/OpenSslPrivateKeyMethod.java
  handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslContext.java
  handler/src/test/java/io/netty/handler/ssl/OpenSslPrivateKeyMethodTest.java
Labels: defect

#9074 Fix flaky GlobalEventExecutorTest.*
  common/src/test/java/io/netty/util/concurrent/GlobalEventExecutorTest.java
Labels: cleanup

#8982 Introduce DynamicAddressConnectHandler which can be used to dynamically change remoteAddress / localAddress when a connect is issued
  handler/src/main/java/io/netty/handler/address/DynamicAddressConnectHandler.java
  handler/src/main/java/io/netty/handler/address/package-info.java
  handler/src/test/java/io/netty/handler/address/DynamicAddressConnectHandlerTest.java
Labels: feature, improvement
