Repository netty/netty, pull requests merged in 2019-10, with the labels that each got.

#9631 Register sun.nio.ch.SelectorImpl fields for unsafe access.
  transport/src/main/resources/META-INF/native-image/io.netty/transport/reflection-config.json
Labels: defect

#9624 Make some inner classes static
  codec-http2/src/main/java/io/netty/handler/codec/http2/AbstractHttp2StreamChannel.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java
Labels: improvement

#9655 Use @SuppressJava6Requirement for animal sniffer plugin to ensure we …
  codec-http/src/main/java/io/netty/handler/codec/spdy/SpdyHeaderBlockZlibEncoder.java
  codec/src/main/java/io/netty/handler/codec/compression/JdkZlibEncoder.java
  common/src/main/java/io/netty/util/internal/LongAdderCounter.java
  common/src/main/java/io/netty/util/internal/NativeLibraryLoader.java
  common/src/main/java/io/netty/util/internal/PlatformDependent.java
  common/src/main/java/io/netty/util/internal/PlatformDependent0.java
  common/src/main/java/io/netty/util/internal/SocketUtils.java
  common/src/main/java/io/netty/util/internal/SuppressJava6Requirement.java
  handler/src/main/java/io/netty/handler/ssl/ExtendedOpenSslSession.java
  handler/src/main/java/io/netty/handler/ssl/Java7SslParametersUtils.java
  handler/src/main/java/io/netty/handler/ssl/Java8SslUtils.java
  handler/src/main/java/io/netty/handler/ssl/Java9SslEngine.java
  handler/src/main/java/io/netty/handler/ssl/Java9SslUtils.java
  handler/src/main/java/io/netty/handler/ssl/JdkSslEngine.java
  handler/src/main/java/io/netty/handler/ssl/OpenSslTlsv13X509ExtendedTrustManager.java
  handler/src/main/java/io/netty/handler/ssl/OpenSslX509Certificate.java
  handler/src/main/java/io/netty/handler/ssl/OpenSslX509TrustManagerWrapper.java
  handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslClientContext.java
  handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslContext.java
  handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslEngine.java
  handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslServerContext.java
  handler/src/main/java/io/netty/handler/ssl/util/OpenJdkSelfSignedCertGenerator.java
  handler/src/main/java/io/netty/handler/ssl/util/SimpleTrustManagerFactory.java
  handler/src/main/java/io/netty/handler/ssl/util/X509TrustManagerWrapper.java
  pom.xml
  testsuite/src/main/java/io/netty/testsuite/transport/socket/DatagramUnicastIPv6Test.java
  transport/src/main/java/io/netty/channel/socket/nio/NioChannelOption.java
  transport/src/main/java/io/netty/channel/socket/nio/NioDatagramChannel.java
  transport/src/main/java/io/netty/channel/socket/nio/NioServerSocketChannel.java
  transport/src/main/java/io/netty/channel/socket/nio/NioSocketChannel.java
  transport/src/main/java/io/netty/channel/socket/nio/ProtocolFamilyConverter.java
Labels: cleanup

#9666 Avoid wrapping scheduled Runnables in Callable adapter
  common/src/main/java/io/netty/util/concurrent/AbstractScheduledEventExecutor.java
  common/src/main/java/io/netty/util/concurrent/PromiseTask.java
  common/src/main/java/io/netty/util/concurrent/ScheduledFutureTask.java
  common/src/main/java/io/netty/util/concurrent/UnorderedThreadPoolEventExecutor.java
Labels: needs_backport

#9718 Fix Http2Headers.method(...) javadocs
  codec-http2/src/main/java/io/netty/handler/codec/http2/Http2Headers.java
Labels: cleanup, documentation
