Repository netty/netty, pull requests merged in 2019-02, with the labels that each got.

#8784 CompositeByteBuf tidy-up
  buffer/src/main/java/io/netty/buffer/CompositeByteBuf.java
Labels: cleanup

#8834 Fix varargs parameter logging in LocationAwareSlf4JLogger
  common/src/main/java/io/netty/util/internal/logging/LocationAwareSlf4JLogger.java
  common/src/test/java/io/netty/util/internal/logging/Slf4JLoggerFactoryTest.java
Labels: defect

#8825 Reduce direct memory overhead per EpollEventLoop when using EpollData…
  transport-native-epoll/src/main/java/io/netty/channel/epoll/NativeDatagramPacketArray.java
Labels: improvement

#8793 Selective Message Aggregation
  codec-http/src/test/java/io/netty/handler/codec/http/HttpObjectAggregatorTest.java
  codec/src/main/java/io/netty/handler/codec/MessageAggregator.java
Labels: defect

#8839 Remove legacy properties
  buffer/src/main/java/io/netty/buffer/AbstractByteBuf.java
  common/src/main/java/io/netty/util/ResourceLeakDetector.java
  common/src/main/java/io/netty/util/internal/PlatformDependent0.java
  microbench/src/main/java/io/netty/microbench/buffer/ByteBufCopyBenchmark.java
Labels: cleanup

#8843 Don't update state of PromiseCombiner when finish(null) is called
  common/src/main/java/io/netty/util/concurrent/PromiseCombiner.java
  common/src/test/java/io/netty/util/concurrent/PromiseCombinerTest.java
Labels: defect

#8847 Support using an Executor to offload blocking / long-running tasks wh…
  handler/src/main/java/io/netty/handler/ssl/DelegatingSslContext.java
  handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslContext.java
  handler/src/main/java/io/netty/handler/ssl/SniHandler.java
  handler/src/main/java/io/netty/handler/ssl/SslContext.java
  handler/src/main/java/io/netty/handler/ssl/SslHandler.java
  handler/src/test/java/io/netty/handler/ssl/CipherSuiteCanaryTest.java
  handler/src/test/java/io/netty/handler/ssl/ConscryptJdkSslEngineInteropTest.java
  handler/src/test/java/io/netty/handler/ssl/ConscryptSslEngineTest.java
  handler/src/test/java/io/netty/handler/ssl/JdkConscryptSslEngineInteropTest.java
  handler/src/test/java/io/netty/handler/ssl/JdkOpenSslEngineInteroptTest.java
  handler/src/test/java/io/netty/handler/ssl/JdkSslEngineTest.java
  handler/src/test/java/io/netty/handler/ssl/OpenSslEngineTest.java
  handler/src/test/java/io/netty/handler/ssl/OpenSslJdkSslEngineInteroptTest.java
  handler/src/test/java/io/netty/handler/ssl/ReferenceCountedOpenSslEngineTest.java
  handler/src/test/java/io/netty/handler/ssl/SSLEngineTest.java
  handler/src/test/java/io/netty/handler/ssl/SslHandlerTest.java
  testsuite/src/main/java/io/netty/testsuite/transport/socket/SocketSslClientRenegotiateTest.java
  testsuite/src/main/java/io/netty/testsuite/transport/socket/SocketSslGreetingTest.java
  transport-native-epoll/src/test/java/io/netty/channel/epoll/EpollDomainSocketSslClientRenegotiateTest.java
  transport-native-epoll/src/test/java/io/netty/channel/epoll/EpollDomainSocketSslGreetingTest.java
  transport-native-epoll/src/test/java/io/netty/channel/epoll/EpollSocketSslClientRenegotiateTest.java
  transport-native-epoll/src/test/java/io/netty/channel/epoll/EpollSocketSslGreetingTest.java
  transport-native-kqueue/src/test/java/io/netty/channel/kqueue/KQueueDomainSocketSslClientRenegotiateTest.java
  transport-native-kqueue/src/test/java/io/netty/channel/kqueue/KQueueDomainSocketSslGreetingTest.java
  transport-native-kqueue/src/test/java/io/netty/channel/kqueue/KQueueSocketSslClientRenegotiateTest.java
  transport-native-kqueue/src/test/java/io/netty/channel/kqueue/KQueueSocketSslGreetingTest.java
Labels: defect, improvement

#8864 Handle null "origin" header in "Old Hixie 75 handshake" as proper bad request.
  codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketServerHandshaker00.java
  codec-http/src/test/java/io/netty/handler/codec/http/websocketx/WebSocketServerHandshaker00Test.java
Labels: defect

#8865 Do not depend on the implementation detail of Unpooled.buffer(int) wh…
  codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketServerHandshaker00.java
Labels: cleanup, defect, improvement

#8863 Include the original Exception that caused the Channel to be closed i…
  transport/src/main/java/io/netty/channel/AbstractChannel.java
  transport/src/main/java/io/netty/channel/ExtendedClosedChannelException.java
  transport/src/test/java/io/netty/channel/AbstractChannelTest.java
Labels: improvement

#8827 Avoid unnecessary char casts for CookieEncoder
  codec-http/src/main/java/io/netty/handler/codec/http/cookie/CookieUtil.java
  codec-http/src/main/java/io/netty/handler/codec/http/cookie/ServerCookieEncoder.java
Labels: cleanup

#8885 DefaultFileRegion.transferTo with invalid count may cause busy-spin
  testsuite/src/main/java/io/netty/testsuite/transport/socket/SocketFileRegionTest.java
  transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollStreamChannel.java
  transport-native-kqueue/src/main/java/io/netty/channel/kqueue/AbstractKQueueStreamChannel.java
  transport/src/main/java/io/netty/channel/AbstractChannel.java
  transport/src/main/java/io/netty/channel/DefaultFileRegion.java
  transport/src/test/java/io/netty/channel/DefaultFileRegionTest.java
Labels: defect

#8895 Further reduce ensureAccessible() overhead
  buffer/src/main/java/io/netty/buffer/AbstractByteBuf.java
  buffer/src/main/java/io/netty/buffer/AbstractDerivedByteBuf.java
  buffer/src/main/java/io/netty/buffer/AbstractReferenceCountedByteBuf.java
  buffer/src/main/java/io/netty/buffer/ByteBuf.java
  buffer/src/main/java/io/netty/buffer/CompositeByteBuf.java
  buffer/src/main/java/io/netty/buffer/SwappedByteBuf.java
  buffer/src/main/java/io/netty/buffer/WrappedByteBuf.java
  buffer/src/main/java/io/netty/buffer/WrappedCompositeByteBuf.java
  microbench/src/main/java/io/netty/buffer/ByteBufAccessBenchmark.java
Labels: improvement
