Repository netty/netty, pull requests merged in 2019-06, with the labels that each got.

#9211 ByteToMessageDecoder.handlerRemoved(...) should only call fireChannel…
  codec/src/main/java/io/netty/handler/codec/ByteToMessageDecoder.java
Labels: cleanup, improvement

#9085 De-duplicate UnpooledDirectByteBuf/UnpooledUnsafeDirectByteBuf
  buffer/src/main/java/io/netty/buffer/UnpooledDirectByteBuf.java
  buffer/src/main/java/io/netty/buffer/UnpooledUnsafeDirectByteBuf.java
Labels: cleanup

#9227 HTTP/2 avoid closing connection when writing GOAWAY
  codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java
  codec-http2/src/test/java/io/netty/handler/codec/http2/Http2FrameCodecTest.java
Labels: defect

#9218 Add support for loopbackmode and accessing the configured interface w…
  testsuite/src/main/java/io/netty/testsuite/transport/socket/DatagramMulticastTest.java
  transport-native-epoll/src/main/c/netty_epoll_linuxsocket.c
  transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollDatagramChannelConfig.java
  transport-native-epoll/src/main/java/io/netty/channel/epoll/LinuxSocket.java
Labels: feature, improvement

#9249 Fix LZ4 encoder/decoder performance with (default) xxHash32
  codec/src/main/java/io/netty/handler/codec/compression/ByteBufChecksum.java
  codec/src/main/java/io/netty/handler/codec/compression/Lz4FrameDecoder.java
  codec/src/main/java/io/netty/handler/codec/compression/Lz4FrameEncoder.java
  codec/src/main/java/io/netty/handler/codec/compression/Lz4XXHash32.java
  codec/src/test/java/io/netty/handler/codec/compression/ByteBufChecksumTest.java
Labels: improvement

#9120 De-duplicate PooledByteBuf implementations
  buffer/src/main/java/io/netty/buffer/AbstractByteBuf.java
  buffer/src/main/java/io/netty/buffer/PooledByteBuf.java
  buffer/src/main/java/io/netty/buffer/PooledDirectByteBuf.java
  buffer/src/main/java/io/netty/buffer/PooledHeapByteBuf.java
  buffer/src/main/java/io/netty/buffer/PooledUnsafeDirectByteBuf.java
Labels: cleanup

#9279 Documented non-usage of BlackHole::consume on ByteBufAccessBenchmark
  microbench/src/main/java/io/netty/buffer/ByteBufAccessBenchmark.java
Labels: cleanup, documentation

#9287 remove unused imports
  buffer/src/test/java/io/netty/buffer/ByteBufDerivationTest.java
  codec-dns/src/main/java/io/netty/handler/codec/dns/DatagramDnsQueryEncoder.java
  codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestEncoderTest.java
  codec-http/src/test/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshakerTest.java
  codec-http2/src/main/java/io/netty/handler/codec/http2/HpackHuffmanDecoder.java
  codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ServerUpgradeCodec.java
  codec-http2/src/test/java/io/netty/handler/codec/http2/DefaultHttp2FrameWriterTest.java
  codec-http2/src/test/java/io/netty/handler/codec/http2/Http2ClientUpgradeCodecTest.java
  codec-http2/src/test/java/io/netty/handler/codec/http2/Http2MultiplexHandlerTest.java
  codec/src/main/java/io/netty/handler/codec/serialization/CompatibleObjectEncoder.java
  codec/src/test/java/io/netty/handler/codec/serialization/CompatibleObjectEncoderTest.java
  common/src/main/java/io/netty/util/concurrent/DefaultPromise.java
  common/src/test/java/io/netty/util/concurrent/PromiseCombinerTest.java
  common/src/test/java/io/netty/util/internal/DefaultPriorityQueueTest.java
  common/src/test/java/io/netty/util/internal/logging/Slf4JLoggerFactoryTest.java
  example/src/main/java/io/netty/example/http2/helloworld/frame/server/Http2OrHttpHandler.java
  handler/src/test/java/io/netty/handler/ssl/ConscryptOpenSslEngineInteropTest.java
  handler/src/test/java/io/netty/handler/ssl/OpenSslJdkSslEngineInteroptTest.java
  handler/src/test/java/io/netty/handler/ssl/PemEncodedTest.java
  handler/src/test/java/io/netty/handler/ssl/SniClientTest.java
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsAddressResolverGroup.java
  resolver-dns/src/main/java/io/netty/resolver/dns/NoopAuthoritativeDnsServerCache.java
  resolver-dns/src/main/java/io/netty/resolver/dns/ShuffledDnsServerAddressStream.java
  resolver-dns/src/test/java/io/netty/resolver/dns/DefaultAuthoritativeDnsServerCacheTest.java
  testsuite-http2/src/main/java/io/netty/testsuite/http2/Http2ServerInitializer.java
  testsuite-native-image/src/main/java/io/netty/testsuite/svm/HttpNativeServer.java
  testsuite-native-image/src/main/java/io/netty/testsuite/svm/HttpNativeServerInitializer.java
  testsuite/src/main/java/io/netty/testsuite/transport/socket/CompositeBufferGatheringWriteTest.java
  testsuite/src/main/java/io/netty/testsuite/transport/socket/SocketConnectTest.java
  transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollChannel.java
  transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollStreamChannel.java
  transport-native-epoll/src/main/java/io/netty/channel/epoll/LinuxSocket.java
  transport-native-epoll/src/test/java/io/netty/channel/epoll/EpollSpliceTest.java
  transport-native-kqueue/src/main/java/io/netty/channel/kqueue/KQueueDatagramChannel.java
  transport-native-kqueue/src/main/java/io/netty/channel/kqueue/KQueueDomainSocketChannelConfig.java
  transport-native-kqueue/src/test/java/io/netty/channel/kqueue/KQueueETSocketAutoReadTest.java
  transport-native-kqueue/src/test/java/io/netty/channel/kqueue/KQueueETSocketExceptionHandlingTest.java
  transport-native-kqueue/src/test/java/io/netty/channel/kqueue/KQueueETSocketReadPendingTest.java
  transport-native-kqueue/src/test/java/io/netty/channel/kqueue/KQueueSocketConnectionAttemptTest.java
  transport/src/main/java/io/netty/channel/CoalescingBufferQueue.java
  transport/src/main/java/io/netty/channel/MultithreadEventLoopGroup.java
  transport/src/main/java/io/netty/channel/PendingWriteQueue.java
  transport/src/main/java/io/netty/channel/socket/nio/NioDatagramChannel.java
  transport/src/test/java/io/netty/channel/DelegatingChannelPromiseNotifierTest.java
  transport/src/test/java/io/netty/channel/socket/nio/NioServerSocketChannelTest.java
Labels: cleanup

#9285 All override methods must be added @override
  buffer/src/main/java/io/netty/buffer/UnpooledUnsafeDirectByteBuf.java
  common/src/main/java/io/netty/util/internal/ThreadLocalRandom.java
  example/src/main/java/io/netty/example/worldclock/WorldClockProtocol.java
  handler/src/main/java/io/netty/handler/ssl/ExtendedOpenSslSession.java
  handler/src/main/java/io/netty/handler/ssl/OpenSslPrivateKey.java
  handler/src/main/java/io/netty/handler/ssl/OpenSslX509Certificate.java
  handler/src/main/java/io/netty/handler/ssl/PemPrivateKey.java
  microbench/src/main/java/io/netty/microbench/channel/EmbeddedChannelWriteReleaseHandlerContext.java
  transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollServerChannelConfig.java
  transport-native-kqueue/src/main/java/io/netty/channel/kqueue/KQueueServerChannelConfig.java
Labels: cleanup

#9273 Reduce coupeling between Http2FrameCodec and Http2Multiplex*
  codec-http2/src/main/java/io/netty/handler/codec/http2/AbstractHttp2StreamChannel.java
  codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ChannelDuplexHandler.java
  codec-http2/src/main/java/io/netty/handler/codec/http2/Http2CodecUtil.java
  codec-http2/src/main/java/io/netty/handler/codec/http2/Http2FrameCodec.java
  codec-http2/src/main/java/io/netty/handler/codec/http2/Http2MultiplexCodec.java
  codec-http2/src/main/java/io/netty/handler/codec/http2/Http2MultiplexHandler.java
  codec-http2/src/main/java/io/netty/handler/codec/http2/MaxCapacityQueue.java
Labels: cleanup
