Repository netty/netty, pull requests merged in 2019-03, with the labels that each got.

#8905 Only remove ReferenceCountedOpenSslEngine from OpenSslEngineMap when …
  handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslEngine.java
Labels: cleanup

#8914 Carefully manage Keep-Alive connections in HttpStaticFileServer
  example/src/main/java/io/netty/example/http/file/HttpStaticFileServerHandler.java
Labels: cleanup, defect

#8921 Do not use GetPrimitiveArrayCritical(...) due multiple not-fixed bugs…
  transport-native-unix-common/src/main/c/netty_unix_socket.c
Labels: cleanup

#8922 HttpContentDecoder must continue read when it did not produce any mes…
  codec-http/src/main/java/io/netty/handler/codec/http/HttpContentDecoder.java
  codec-http/src/test/java/io/netty/handler/codec/http/HttpContentDecompressorTest.java
Labels: defect

#8902 Optimize Hpack and AsciiString hashcode and equals
  common/src/main/java/io/netty/util/internal/PlatformDependent.java
  common/src/main/java/io/netty/util/internal/PlatformDependent0.java
Labels: improvement

#8924 Fix HttpUtil.isKeepAlive to behave correctly when Connection is a comma separated list
  codec-http/src/main/java/io/netty/handler/codec/http/HttpUtil.java
  codec-http/src/test/java/io/netty/handler/codec/http/HttpUtilTest.java
Labels: defect

#8949 Correctly produce ssl alert when certificate validation fails on the …
  handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslClientContext.java
  handler/src/test/java/io/netty/handler/ssl/SslErrorTest.java
Labels: defect

#8945 Expose the global direct memory counter.
  common/src/main/java/io/netty/util/internal/PlatformDependent.java
Labels: feature, improvement

#8960 AbstractChannelHandlerContext doesn't need to extend DefaultAttributeMap
  transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java
Labels: cleanup

#8941 Allow to automatically trim the PoolThreadCache in a timely interval
  buffer/src/main/java/io/netty/buffer/PooledByteBufAllocator.java
  buffer/src/test/java/io/netty/buffer/PooledByteBufAllocatorTest.java
  common/src/main/java/io/netty/util/concurrent/FastThreadLocal.java
  common/src/main/java/io/netty/util/concurrent/GlobalEventExecutor.java
  common/src/main/java/io/netty/util/concurrent/SingleThreadEventExecutor.java
  common/src/main/java/io/netty/util/internal/ThreadExecutorMap.java
  common/src/test/java/io/netty/util/concurrent/FastThreadLocalTest.java
  common/src/test/java/io/netty/util/internal/ThreadExecutorMapTest.java
Labels: feature, improvement

#8946 Fix possible ByteBuf leak when CompositeByteBuf is resized
  buffer/src/main/java/io/netty/buffer/CompositeByteBuf.java
  buffer/src/test/java/io/netty/buffer/AbstractCompositeByteBufTest.java
Labels: defect

#8970 Correctly detect exeception cause when using BoringSSL in SslErrorTest
  handler/src/test/java/io/netty/handler/ssl/SslErrorTest.java
Labels: cleanup
