Repository netty/netty, pull requests merged in 2019-01, with the labels that each got.

#8711 Remove unnecessary loop variable from `AsciiString`.
  common/src/main/java/io/netty/util/AsciiString.java
  common/src/test/java/io/netty/util/AsciiStringCharacterTest.java
Labels: cleanup

#8718 Access the Constructor of the Channel in the constructor of Reflectiv…
  transport/src/main/java/io/netty/channel/ReflectiveChannelFactory.java
Labels: improvement

#8720 cleanup: extract duplicate code into method
  common/src/main/java/io/netty/util/concurrent/SingleThreadEventExecutor.java
Labels: cleanup

#8716 Correctly propagate write failures from ChunkedWriteHandler
  handler/src/main/java/io/netty/handler/stream/ChunkedWriteHandler.java
  handler/src/test/java/io/netty/handler/stream/ChunkedWriteHandlerTest.java
Labels: defect

#8731 Only handle NXDOMAIN as failure when nameserver is authoritive or no …
  resolver-dns/src/main/java/io/netty/resolver/dns/DnsResolveContext.java
  resolver-dns/src/test/java/io/netty/resolver/dns/DnsNameResolverTest.java
Labels: defect

#8726 Ensure FlowControlled data frames will be correctly removed from the …
  codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionEncoder.java
  codec-http2/src/test/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionEncoderTest.java
  codec-http2/src/test/java/io/netty/handler/codec/http2/Http2ConnectionRoundtripTest.java
Labels: defect

#8735 Fix racy ChannelOutboundBuffer.testWriteTaskRejected test.
  transport/src/test/java/io/netty/channel/ChannelOutboundBufferTest.java
Labels: cleanup

#8738 Fix flaky ChannelInitializerTest.testChannelInitializerEventExecutor()
  transport/src/test/java/io/netty/channel/ChannelInitializerTest.java
Labels: cleanup

#8773 Fix three bugs in CompositeByteBuf
  buffer/src/main/java/io/netty/buffer/CompositeByteBuf.java
  buffer/src/test/java/io/netty/buffer/AbstractCompositeByteBufTest.java
Labels: defect

#8798 Fix AppendableCharSequence.subSequence(...) where start == end.
  common/src/main/java/io/netty/util/internal/AppendableCharSequence.java
  common/src/test/java/io/netty/util/internal/AppendableCharSequenceTest.java
Labels: defect

#8815 Compare HttpMethod by reference
  codec-http/src/main/java/io/netty/handler/codec/http/HttpContentEncoder.java
  codec-http/src/main/java/io/netty/handler/codec/http/HttpMethod.java
  codec-http/src/main/java/io/netty/handler/codec/http/HttpServerCodec.java
  codec-http/src/main/java/io/netty/handler/codec/http/cors/CorsHandler.java
  codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketServerProtocolHandshakeHandler.java
  codec-http/src/main/java/io/netty/handler/codec/rtsp/RtspMethods.java
  example/src/main/java/io/netty/example/http/file/HttpStaticFileServerHandler.java
  example/src/main/java/io/netty/example/http/upload/HttpUploadServerHandler.java
  example/src/main/java/io/netty/example/http/websocketx/benchmarkserver/WebSocketServerHandler.java
  example/src/main/java/io/netty/example/http/websocketx/server/WebSocketIndexPageHandler.java
  testsuite-autobahn/src/main/java/io/netty/testsuite/autobahn/AutobahnServerHandler.java
Labels: improvement

#8800 #7756 Add @Sharable TYPE_USE support for inner class annotations
  transport/src/main/java/io/netty/channel/ChannelHandler.java
  transport/src/main/java/io/netty/channel/ChannelHandlerAdapter.java
  transport/src/test/java/io/netty/channel/ChannelHandlerAdapterTest.java
Labels: feature, improvement

#8797 Do not schedule notify task if there are no listeners attached to the…
  common/src/main/java/io/netty/util/concurrent/DefaultPromise.java
  common/src/test/java/io/netty/util/concurrent/DefaultPromiseTest.java
Labels: improvement
